### ISSUE TITLE
State all models that we have to make.

### ISSUE THREAD

**Issue by nilinswap** [atulsinha007/ML#3]

**Comment by atulsinha87** [comment]
1. KNN
2. Centroid Classifier Algorithm
3. Perceptron: i) Batch perceptron ii) Mini batch perceptron
4. MLP (fully connected) 
-different activation functions (sigmoid, tanh, ReLU, exp ReLU, leaky ReLU)
-varying i) step size ii) velocity iii) momentum
-dataset: i) Iris ii) 2moon
